"""add user_preferences

迁移 ID: 45d7006e569e
父迁移: 17c40f39f343
创建时间: 2025-06-30 19:43:34.644273

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "45d7006e569e"
down_revision: str | Sequence[str] | None = "17c40f39f343"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "muicebot_plugin_memory_userprofile", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "preferences",
                sa.Text(),
                nullable=False,
                comment="用户偏好（列表映射为字符串）",
            )
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "muicebot_plugin_memory_userprofile", schema=None
    ) as batch_op:
        batch_op.drop_column("preferences")

    # ### end Alembic commands ###
